### ISSUE TITLE
pkg-config is transformed to pkgconfig(pkg-config)

### ISSUE THREAD

**Issue by plusky** [openSUSE/spec-cleaner#105]
spec-clener -p will change following:
`BuildRequires: pkg-config`
to:
`BuildRequires: pkgconfig(pkg-config)`

It seems that pkg-config itself should be blacklisted

**Comment by scarabeusiv** [comment]
Also we should add it if missing and pkgconfig(bleh) br/r is present.

**Comment by scarabeusiv** [comment]
Should be fixed now.
