### ISSUE TITLE
pkgconfig not recognised

### ISSUE THREAD

**Issue by plusky** [openSUSE/spec-cleaner#117]
With tmux, spec-cleaner does following:
```
# osc diff
...
 BuildRequires:  automake
+BuildRequires:  pkg-config
 BuildRequires:  pkgconfig

```
It seems that either pkgconfig should be recognised, and pkg-config not added in this case or pkgconfig should be replaced by pkg-config.

**Comment by scarabeusiv** [comment]
Actually lest take it the other way around and use pkgconfig because it works on fedoras too.
