### ISSUE TITLE
venv installation not working (ERROR: No such file or directory)

### ISSUE THREAD

**Issue by toabctl** [openSUSE/spec-cleaner#128]
When installing spec-cleaner in a virtual env, it's not working:
```
virtualenv test
$ source test/bin/activate
$ pip install spec-cleaner
$ echo Name: foobar > foobar.spec
$ spec-cleaner foobar.spec 
ERROR: No such file or directory
```

The problem is that spec-cleaner tries to find ```excludes-bracketing.txt``` and is looking in the wrong directory for that.

**Comment by scarabeusiv** [comment]
Check https://pythonhosted.org/setuptools/pkg_resources.html#resourcemanager-api
