### ISSUE TITLE
_find_macros_with_arg in rpmregexp does nothing

### ISSUE THREAD

**Issue by scarabeusiv** [openSUSE/spec-cleaner#131]
https://github.com/openSUSE/spec-cleaner/blob/master/spec_cleaner/rpmregexp.py#L200

I am not sure what it was supposed to do but no test in the testsuite hit the condition. Could you please figure it out as it is your code?

**Comment by sleep-walker** [comment]
This code should detect local macros with arguments
```
%define some_useful_macro(... \
                          ...)
```
I'm not sure if it is relevant but it looks like the intention was to exclude found macro functions from putting braces around (because they can be multiline?)...

**Comment by scarabeusiv** [comment]
As I told on irc, if it works then it is nice, but we should have at least one testcase actually checking for the functionality please.

**Comment by scarabeusiv** [comment]
Found the culprit and fixed :)
