### ISSUE TITLE
Drop redundant pkgconfig requires

### ISSUE THREAD

**Issue by jengelh** [openSUSE/spec-cleaner#133]
Certain new versions of spec-cleaner started adding pointless Requires: pkgconfig to openSUSE -devel subpackages (e.g. https://build.opensuse.org/request/show/396557 )
```
 Group:          Development/Libraries/C and C++
 Requires:       liblastfm5-1 = %{version}
 Requires:       liblastfm_fingerprint5-1 = %{version}
+Requires:       pkgconfig
 Requires:       pkgconfig(Qt5Core)
 Requires:       pkgconfig(Qt5DBus)
 Requires:       pkgconfig(Qt5Network)
```
but rpm is smart enough to automatically add this already if it sees a `.pc` file in the `%files` list.

**Comment by scarabeusiv** [comment]
But that does not work in case of when you only require some pkgconfig variables and do not provide one yourself.

We have packages that have requires: pkgconfig(something) and yet do not provide that.

**Comment by jengelh** [comment]
I do not understand what you mean by that. Where would I, once lastfm-devel is installed, require "some" (which?) pkgconfig variable?

**Comment by scarabeusiv** [comment]
Package has .pc file and the pkgconfig style requires:

rpm -qpR /var/tmp/build-root/openSUSE_Factory-x86_64/home/abuild/rpmbuild/RPMS/x86_64/libwps-devel-0.4.3-0.x86_64.rpm
/usr/bin/pkg-config
libwps-0_4-4 = 0.4.3
pkgconfig(glu)
pkgconfig(librevenge-0.0)
rpmlib(CompressedFileNames) <= 3.0.4-1
rpmlib(PayloadFilesHavePrefix) <= 4.0-1
rpmlib(PayloadIsLzma) <= 4.4.6-1

Package has no .pc file and pkgconfig style requires:

rpm -qpR /var/tmp/build-root/openSUSE_Factory-x86_64/home/abuild/rpmbuild/RPMS/x86_64/libwps-devel-0.4.3-0.x86_64.rpm
libwps-0_4-4 = 0.4.3
pkgconfig(glu)
rpmlib(CompressedFileNames) <= 3.0.4-1
rpmlib(PayloadFilesHavePrefix) <= 4.0-1
rpmlib(PayloadIsLzma) <= 4.4.6-1

**Comment by jengelh** [comment]
What are you trying to point out here? If libwps-devel has no libwps.pc file, then there is indeed no need to require pkgconfig, because there is no libwps.pc file you could possibly query. glu is freestanding in that sense that it can and will take care of pkgconfig on its own the very same way.

**Comment by scarabeusiv** [comment]
if you now have package that has ONLY libwps-devel in its deps it won't pull in pkgconfig and fail on the interpretation of pkgconfig(glu).

**Comment by jengelh** [comment]
Installing such a libwps-devel would cause the solver to go looking for `pkgconfig(glu)`. The solver will find this symbol in glu-devel.rpm and select that for installation. It will do so even in the absence of pkg-config at the time the solver is running. There is no special interpretation of `pkgconfig(glu)` happening.
