### ISSUE TITLE
Sudden decurlification of variables

### ISSUE THREAD

**Issue by jengelh** [openSUSE/spec-cleaner#134]
In https://build.opensuse.org/request/show/396657 , spec-cleaner has turned
```
%ifarch %{ix86}
```
into
```
%ifarch %ix86
```
which is wrong when the general mantra of curlifying variable names is to be followed.

**Comment by scarabeusiv** [comment]
Yep, someone complained aboit ix86 in 2014 so we put that one there and to keep in sync with others we just added the rest, because just one without the brackets looks stupid.

Feel free to PR removal of them (make sure the testsuite passes).
