### ISSUE TITLE
Inconsistent (de)curlification

### ISSUE THREAD

**Issue by jengelh** [openSUSE/spec-cleaner#136]
The original idea for data/excludes-bracketing.txt appears to have been to curlify everything that is not a built-in non-expanding RPM directive. The list however misses that goal, and instead is comprised of a heterogenous mixture of both, which causes specfiles to have inconsistent curlification all over the place for no apparent reason. %cabal_test is excluded but %cabal is not. %ghc_pkg_recache is excluded but %ghc_suse_disable_debug_packages is not.

**Comment by mimi1vx** [comment]
@jengelh  internal macros not used in specfiles directly .

**Comment by scarabeusiv** [comment]
Well since Ondrej created those macros I suppose we can close this.
