### ISSUE TITLE
Please add two new groups to allowed_groups.txt

### ISSUE THREAD

**Issue by marguerite** [openSUSE/spec-cleaner#139]
* devel:languages:golang
* devel:languages:nodejs

those two devel projects should have a rpm group each, eg:

* Devel/Languages/Go
* Devel/Languages/NodeJS

**Comment by scarabeusiv** [comment]
Was this approved on the packaging ml and included in the wiki and RPM?

If it was feel free to create pullrequest.

**Comment by marguerite** [comment]
@scarabeusiv included in RPM? how? I've been thinking about adding those terms for almost 2 years, just never find which file openSUSE stores those groups. the one in `rpm` package stores upstream (RHEL/Fedora)'s. Maybe a little help?

**Comment by scarabeusiv** [comment]
We have them on wiki (which is on top of https://github.com/openSUSE/spec-cleaner/blob/master/data/allowed_groups.txt)

Then there should be rpmlint check verifying them, not sure about that. Maybe try writting email to the rpm maintainer.

**Comment by scarabeusiv** [comment]
Please reopen when rpm package and the wiki are containing the groups.
