### ISSUE TITLE
Use %make_install by default

### ISSUE THREAD

**Issue by plusky** [openSUSE/spec-cleaner#143]
As all currently supported openSUSE releases support `%make_install` perhaps it's time to consider defaulting to it instead of `make install DESTDIR=%{buildroot}`

**Comment by sleep-walker** [comment]
Is `%makeinstall` supported less? It would make it compatibile with Fedora.

**Comment by scarabeusiv** [comment]
That one is actually bad,  it is implemented in each rpm distro differently.

Unified version is %make_install and it is in all of the recent ones.
