### ISSUE TITLE
Do not touch existing copyright header

### ISSUE THREAD

**Issue by smithfarm** [openSUSE/spec-cleaner#144]
If there is a copyright header in the spec file, spec-cleaner should not touch it.

In https://build.opensuse.org/package/rdiff/filesystems:ceph/ceph?linkrev=base&rev=39 can be seen what is left of the ceph.spec copyright header after spec-cleaner munged it. The original was aligned with the upstream copyright header and should not (must not!) be changed.

*No* automated tools should modify copyright statements - there are legal ramifications to doing that!

**Comment by scarabeusiv** [comment]
Sorry there already is an option for spec-cleaner to ignore copyright. Also it is mandatory for spec-files in our distribution to have the MIT header we put there. So you have to override it.

**Comment by DimStar77** [comment]
??? Where is that mandate coming from for our spec files to be MIT  ???

**Comment by DimStar77** [comment]
the mandate can''t be real, as the text added to the standard spec files is:

> # All modifications and additions to the file contributed by third parties
> # remain the property of their copyright owners, unless otherwise agreed
> # upon. The license for this file, and modifications and additions to the
> # file, is the same license as for the pristine package itself (unless the
> # license for the pristine package is not an Open Source License, in which
> # case the license is the MIT License). An "Open Source License" is a
> # license that conforms to the Open Source Definition (Version 1.9)
> # published by the Open Source Initiative.

So the .spec file by definition is of the license of the package, NOT MIT.

In Nathan's case, the header clearly stated the .spec is LGPL-2.1 (the package itself has an aggregation of licenses, so this clarification in the header is actually important - the default text would result in choice of license for the .spec file).

Hence, the claim that MIT is mandated can;'t be true

**Comment by DimStar77** [comment]
And as for the option: not mangling existing copyright preamble has to be part of the 'standard' mode used by the source-service - the variant running automatiically on "osc ci"

**Comment by scarabeusiv** [comment]
I had this discussion with Stefan in past and we allowed only the MIT.

Also it was one of the must features of the osc-service_format_spec_file so if you change this you should discuss this with everyone involved I guess.

I already have the option so for me it is just changing one value in setup to not mangle it on the run.

@coolo any insights what is desired then?

**Comment by DimStar77** [comment]
> I had this discussion with Stefan in past and we allowed only the MIT.
is an interesting statement - especially considering that the text clearly puts MIT only as fallback if the package in question does not use an open-source license - otherwise the package license is applicable

**Comment by scarabeusiv** [comment]
Okey what I had on my mind is that it has to have this header stated with the fallback put in there.
It was requested I suppose by legal@? And I was told it has to be there.
But as I said, i don't care much, it is just one line in spec-cleaner code to not do it by default.

**Comment by coolo** [comment]
we need a license header in the spec file - and the challenge is detecing random text from a license. But prepare_spec always removes licenses and only leaves copyright lines intact. But that's because it's dumb.

What I would expect: leave valid licenses intact, but add the openSUSE license text if there is no license to detect.

**Comment by scarabeusiv** [comment]
Okay licenses detection, should i just store most common license strings and match up the content on top of the spec-file against them? Some people get really creative with the header, do we maybe have some examples of what we would like to preserve?

Also to be exact: the bug natan reports is output of the old format_spec_file not done by spec-cleaner ;-) Not that in the header case it would behave the same.

**Comment by smithfarm** [comment]
Well, it's true that it leaves existing copyright lines intact, and that carefully worded statement is true. However, it does modify the copyright by adding this line before any existing copyrights:

```
# Copyright (c) 2016 SUSE LINUX GmbH, Nuernberg, Germany.
```

This blindly assumes that the spec file is either entirely written by SUSE or has some SUSE-written content in it.

In our case, the Ceph spec file is maintained as a community effort, and it's not appropriate to name any companies explicitly.

Having "osc ci" automatically mangle the copyright declaration in this way is unfortunate.

**Comment by coolo** [comment]
well, the whitespace is ours :)

The ceph spec file is one out of 9200 in Factory - and I object changing a default that works for 9199. Use  osc ci --skip-local-service-run

**Comment by scarabeusiv** [comment]
Lets close this one and "fix" it by resolving issue #148
