### ISSUE TITLE
Suspicious pkgconfig suggestions

### ISSUE THREAD

**Issue by hwoarang** [openSUSE/spec-cleaner#145]
So I get this with 0.9.0

```
@@ -26,7 +25,6 @@
 # The testsuite is somewhat fragile for continuous testing in OBS
 # but keep it here as an option
 %bcond_with check
-
 Name:           openvswitch
 Version:        2.5.0
 Release:        0
@@ -53,12 +51,13 @@
 BuildRequires:  make
 BuildRequires:  openssl
 BuildRequires:  perl
-BuildRequires:  pkgconfig(openssl)
+BuildRequires:  pkgconfig
 # Needed by the testsuite
 BuildRequires:  procps
 BuildRequires:  python-devel
 BuildRequires:  python-xml
 BuildRequires:  valgrind-devel
+BuildRequires:  pkgconfig(openssl)
```

So apart from the removal of the first empty line which I find it slightly annoying, the pkgconfig suggestions are a bit suspicious. Why do you want me to explicitly depend on pkgconfig? The package which provides the ```openssl``` pkgconfig file already pulls in the ```pkg-config``` tool

```
abuild@helix:/home/abuild> rpm -q --requires libopenssl-devel
/usr/bin/pkg-config
libopenssl1_0_0 = 1.0.2h
openssl = 1.0.2h
pkgconfig(libcrypto)
pkgconfig(libssl)
rpmlib(CompressedFileNames) <= 3.0.4-1
rpmlib(PayloadFilesHavePrefix) <= 4.0-1
rpmlib(PayloadIsLzma) <= 4.4.6-1
zlib-devel
```

Am I missing something here?

**Comment by scarabeusiv** [comment]
Actually you need pkgconfig package to translate the pkgconfig(bla). If nothing else depends on it then it won't be pulled in and your package would fail. So it is safer to put there. I guess for you python-devel pulls it in so it owuld work without it.

For the newline after bconds, it is just cosmetics decided by the rpmpreamble.py that everything should be one huge list, if you feel like empty spaces would really improve the readability feel free to add them in that file where applicable.
