### ISSUE TITLE
Add parser variable that would prevent package to be parsed by spec-cleaner

### ISSUE THREAD

**Issue by scarabeusiv** [openSUSE/spec-cleaner#148]
Discussed on -factory with Dimstar, mostly about some string like "# nospeccleaner" to prevent superspecial packages to be altered. (mostly mentioned with ceph package).

**Comment by scarabeusiv** [comment]
@DimStar77 do you have any prefference for the name of the comment? Is the above okay?

**Comment by DimStar77** [comment]
I'm unsure between
 "# nospeccleaner"
and
 "# skip-spec-cleaner"

In the end, it does not really matter - it's for very special cases only anyway

**Comment by smithfarm** [comment]
+1

**Comment by smithfarm** [comment]
@scarabeusiv I can put the line anywhere in the spec file, correct? For example, it could be the very last line at the end.

**Comment by scarabeusiv** [comment]
Exactly, it can be anywhere.

**Comment by sleep-walker** [comment]
I really don't like this feature. I hope it will be used just rarely.

**Comment by smithfarm** [comment]
@sleep-walker It's not a feature. It's providing a knob (which was missing) to disable a feature.
