### ISSUE TITLE
Invalid refactoring of Requires-section

### ISSUE THREAD

**Issue by susnux** [openSUSE/spec-cleaner#150]
I discovered a strange behavior of spec-cleaner, in the spec file I have this block:

```
%define dep_postfix %{nil}
%ifarch x86_64
  %define dep_postfix -32bit
%endif
Requires:       alsa%{dep_postfix} >= 1.0.23
```

spec-clean produces this output:

```
Requires:       1.0.23
Requires:       alsa%{dep_postfix}
```

I am using version 0.9.0 from openSUSE Leap 42.1.

Attached is the spec file before modification (yes .txt because github can not handle other formats...).
[steam.spec.txt](https://github.com/openSUSE/spec-cleaner/files/417870/steam.spec.txt)

**Edit**: I tried also the current git version, but same issue.

**Comment by sleep-walker** [comment]
Pushed commit should eliminate all the problems with using regexp instead of parser. Currently it pass all the tests.
