### ISSUE TITLE
ERROR: File 'excludes-bracketing.txt' not found in datadirs

### ISSUE THREAD

**Issue by yac** [openSUSE/spec-cleaner#152]
I get the error in title on Fedora with

    pip install --user spec-cleaner
    spec-cleaner some.spec

Running manually with

    git clone https://github.com/openSUSE/spec-cleaner
    cd spec-cleaner
    python setup.py develop --user

works as expected. Maybe data files aren't included in sdist tarball?

**Comment by scarabeusiv** [comment]
Could you please check where pip install all the files for the spec-cleaner?

sdist seem to list it properly, maybe it was put in wrong directory...

**Comment by scarabeusiv** [comment]
Ah the --user installs it in ~/.local/share/spec-cleaner/ and thus it can't be found because that logic is not there.

It is defined in https://github.com/openSUSE/spec-cleaner/blob/master/spec_cleaner/fileutils.py#L26 
Could you create some patch for this?
