### ISSUE TITLE
BuildIgnore incorrectly removed

### ISSUE THREAD

**Issue by plusky** [openSUSE/spec-cleaner#153]
On qa_test_clamav, following occurs:
`-#!BuildIgnore: post-build-checks-malwarescan`

**Comment by scarabeusiv** [comment]
It is technically removed correctly the buildignore is commentary known by buildservice only and andrej put it to HEADER section, which gets wiped out and created anew...

**Comment by scarabeusiv** [comment]
I have to close this as cantfix, there is no way how to catch this apart from user review of the resulting diff :(
