### ISSUE TITLE
custom %if-like conditionals don't work

### ISSUE THREAD

**Issue by matejcik** [openSUSE/spec-cleaner#161]
In rpm, macro starting with `%if` must be some kind of conditional, a redefinition of `%if (something)`. At this point, spec-cleaner does not recognize this fact. This breaks `%ifpython2` `%ifpython3` and friends from the new python macroset, because they are not treated as a start of a conditional block, and reordered wherever.

**Comment by sleep-walker** [comment]
Either we can define category for custom %if-like macros to be (filled and) properly recognized, or we can add `%ifpython2` and `%ifpython3` to whitelist. Or you can use `%if %some_condition` instead.

**Comment by matejcik** [comment]
as far as I could tell, it's correct to treat `^%if.*$` the same way as the usual `%if something`, no need to whitelist anything
