### ISSUE TITLE
Weird behavior with commented patch

### ISSUE THREAD

**Issue by mvyskocil** [openSUSE/spec-cleaner#17]
home:Ignotusp:devel:languages:rust/rust/rust.spec

before
#Patch0:    rust64bit.patch

BuildRequires: gcc-c++
BuildRequires: python
BuildRequires: perl
BuildRequires: curl
BuildRequires: chrpath

BuildConflicts: brp-check-suse

after
BuildRequires:  chrpath
BuildRequires:  curl
#Patch0:    rust64bit.patch
BuildRequires:  gcc-c++
BuildRequires:  perl
BuildRequires:  python
BuildConflicts: brp-check-suse

**Comment by scarabeusiv** [comment]
After thinking about this and leaving it open for so long lets just pretend everything with # is commentary and do not try to be smart about the content of the commentary.
