### ISSUE TITLE
spec-cleaner expands %{__python2} macro into python2

### ISSUE THREAD

**Issue by javierpena** [openSUSE/spec-cleaner#173]
spec-cleaner 0.9.3 now expands macros like %{__python2} into their equivalents (python2). However, this is already done by the python2 RPM macros, at least in Fedora and CentOS. This is causing some jobs in the OpenStack rpm-packaging project to fail, see [1] as an example.

[1] http://logs.openstack.org/14/440814/1/check/gate-rpm-packaging-tox-lint-ubuntu-xenial/86246ab/console.html

**Comment by scarabeusiv** [comment]
That is correct behaviour from our point of view. Even in fedora/centos they do not need to use those macros.

**Comment by javierpena** [comment]
I don't think this is correct. If we look at https://fedoraproject.org/wiki/Packaging:Python#Macros, the Fedora Packaging guidelines for Python recommend using %{__python2}, and the provided example spec file does it. Where is the guideline against this?

**Comment by scarabeusiv** [comment]
We are not developing this for fedora and our guidelines preffer the non-macroed syscalls.

I am not saying fedora does not have this guideline but I am saying it is not needed in regards to their use of koji and other tools.

**Comment by dirkmueller** [comment]
@scarabeusiv is there a way to stop doing this with the -m switch or some other cmdline option?

**Comment by scarabeusiv** [comment]
Not at the moment. It is run everytime for all lines:

https://github.com/openSUSE/spec-cleaner/blob/master/spec_cleaner/rpmsection.py#L179

Simply put you can of course patch it with some other option, but honestly you want those conversions to happen, those macros are quite useless.
