### ISSUE TITLE
No python-base in centos, fedora etc

### ISSUE THREAD

**Issue by rgarrigue** [openSUSE/spec-cleaner#18]
C/C from https://bugzilla.novell.com/show_bug.cgi?id=856838

Require: python-base is only available in suse. Could you tweak the Require for
spec-cleaner to work over centos, fedora etc please.

For more precision, I'm think about a "if suse Requires python-base else Requires python, python-???".
I can't tell you what are the python-??? you need for spec cleaner, but here are an example of distro-conditionnal blocks in spec:

```
# RHEL <=5
%if 0%{?rhel} && 0%{?rhel} <= 5
BuildRequires: python26-devel
Requires: python26
%endif

# RHEL > 5
%if 0%{?rhel} && 0%{?rhel} > 5
BuildRequires: python-devel
Requires: python
%endif

# FEDORA > 17
%if 0%{?fedora} >= 18
BuildRequires: python-devel
Requires: python%endif
%endif

# SuSE/openSuSE
%if 0%{?suse_version}
BuildRequires: python-devel
BuildRequires: python-setuptools
Requires: python-paramiko
Requires: python-jinja2
Requires: python-keyczar
Requires: python-yaml
Requires: python-httplib2
%endif
```

NB, %else also exist iirc

**Comment by scarabeusiv** [comment]
By default we do not handle the suse compatiblity with other distros, but patches with testsuite update are welcome.

**Comment by sleep-walker** [comment]
I'd rather see opensuse-specific macros implemented on other OBS distributions projects. It's cleaner and more useful.

**Comment by sleep-walker** [comment]
OK, it seems I took it completely wrong and I'm talking about different problem :)

**Comment by scarabeusiv** [comment]
As this is just pretty corner-case of the spec writing we won't work toward this. But if someone provides patches they will be merged.
