### ISSUE TITLE
PreReq containing macros are mangled

### ISSUE THREAD

**Issue by plusky** [openSUSE/spec-cleaner#180]
`PreReq:         /bin/rm /bin/mkdir /usr/bin/chroot %fillup_prereq %insserv_prereq` is transformed to:
```
PreReq:         /bin/mkdir%{_bindir}/chroot%fillup_prereq%insserv_prereq
PreReq:         /bin/rm
```

**Comment by scarabeusiv** [comment]
The issue is in the parser of the deps.

@sleep-walker it again end in endless loop, se the latest test commit

**Comment by sleep-walker** [comment]
Nasty but needed one, thanks for the report.
