### ISSUE TITLE
Incorrect addition of FIXME

### ISSUE THREAD

**Issue by DimStar77** [openSUSE/spec-cleaner#182]
While running spec-cleaner over bundle-lang-common, spec-cleaner keeps on adding:

> FIXME: Use %requires_eq macro instead

even though the lines below look like:
> Provides:       NetworkManager-lang = %(rpm -q --queryformat '%{VERSION}' NetworkManager-lang)\

The fixme is definitively wrong: this cannot be replaced with a %requires_eq.

Would be great if this noise is not added to the spec files there

**Comment by scarabeusiv** [comment]
As a temporary workaround add there any comment above this, it will force spec-cleaner to not add the FIXME.
