### ISSUE TITLE
Incorrect handling of descriptions with line of format "keyword: some more text"

### ISSUE THREAD

**Issue by Tracerneo** [openSUSE/spec-cleaner#184]
I have ran into a bug, where spec-cleaner will incorrectly modify description, if one of the lines begins with a known tag followed by a colon.

Example:
```diff
 %description
 This project contains reference implementations, test cases, and other
 documents under source code control for Java Specification Request 305:
 Annotations for Software Defect Detection. More information at the Google
-group: http://groups.google.com/group/jsr-305.
+
+Group:          http://groups.google.com/group/jsr-305.
 ```

Another example:
```%description
This is a description that
provides:
some information
```
gets turned into
```%description
This is a description that

License:   
some information
```

**Comment by scarabeusiv** [comment]
Fun thing, the non-capitals version is parsed by RPM and actually intepreted, even in %description, the requirement is to have there empty line...

I wonder how to detect for this sanely....

**Comment by scarabeusiv** [comment]
Probably best would be to give up on the case-sensitivity if we at least once leave the preamble section...
