### ISSUE TITLE
License and/or etc should be capitalised by the specification

### ISSUE THREAD

**Issue by scarabeusiv** [openSUSE/spec-cleaner#189]
format_spec_file:
obs-service-format_spec_file/issues/21
https://github.com/openSUSE/obs-service-format_spec_file/pull/22

**Comment by scarabeusiv** [comment]
@DimStar77 is this still correct and should it be auto replaced with the capitalised forms? See the discussion on the PR in format_spec_file above.

**Comment by DimStar77** [comment]
AND/OR are indeed supposed to be capitalised
