### ISSUE TITLE
Do not set defattr on the files

### ISSUE THREAD

**Issue by scarabeusiv** [openSUSE/spec-cleaner#194]
If in default value it is equal to what rpm already does -> less lines.

**Comment by luizluca** [comment]
@scarabeusiv , this introduces a warning for SLE12 packages.
Should I add something in my project config or rpmlintrc to avoid it?

**Comment by luizluca** [comment]
For SLE11, it even breaks build

**Comment by scarabeusiv** [comment]
That is on purpose, the warning on SLE12 is nill and was there only for sle11 compatibility.

As having support in spec-files prepared for SLE15 to build them on sle11 is bit overkill we always plan to support -1 of the codestreams. You can fix this by projectcfg declaration in obs to make even sle11 work, it just does not have the default value that is present since openSUSE 12.0.
