### ISSUE TITLE
Change SUSE-NonFree to NonFree

### ISSUE THREAD

**Issue by tomschr** [openSUSE/spec-cleaner#213]
According to Ciaran, the SUSE-NonFree license will be NonFree.

**Comment by scarabeusiv** [comment]
It is auto regenerated using the make command in the git repo, unless something broke

**Comment by scarabeusiv** [comment]
Aand it is broken.... :D

sh license-update.sh
DUPS Y
make: *** [Makefile:21: data/licenses_changes.txt] Chyba 1

**Comment by scarabeusiv** [comment]
Oky should be regenerated on Master
