### ISSUE TITLE
%license replacement issue

### ISSUE THREAD

**Issue by szotsaki** [openSUSE/spec-cleaner#220]
`ringtones/default.wav.LICENSE` got replaced with `ringtones/default.wav.` when running the latest Tumbleweed version of spec-cleaner:

``` diff
-%doc AUTHORS COPYING README NEWS ChangeLog ringtones/default.wav.LICENSE
+%license COPYING
+%doc AUTHORS README NEWS ChangeLog ringtones/default.wav.
```

I also would like to ask if `%license` is recognised by openSUSE 42.2 (rpm 4.11.2)?

**Comment by scarabeusiv** [comment]
It is recognised by openSUSE 42.3 which is only currently supported openSUSE.

And yep that is a bug... thanks for it
