### ISSUE TITLE
Special handling for 'pattern' packages

### ISSUE THREAD

**Issue by DimStar77** [openSUSE/spec-cleaner#224]
Given this input spec file:

```
%package apparmor
%pattern_basetechnologies
Summary:        AppArmor
Group:          Metapackages
Provides:       patterns-openSUSE-apparmor = %{version}
Provides:       pattern() = apparmor
Provides:       pattern-icon() = pattern-apparmor
Provides:       pattern-order() = 1100
Provides:       pattern-visible()
Obsoletes:      patterns-openSUSE-apparmor < %{version}
Requires:       pattern() = minimal_base
%if 0%{?is_opensuse}
Recommends:     pattern() = apparmor_opt
%endif
Requires:       wget
Recommends:     curl

%changelog
```

The order is pretty ok (I can live with the obsoletes being moved down, that would be acceptable), but what it currently does is move wget and curl in fron of all the special pattern* stuff; considering that the pattern* stuff is the 'most essential' for this package, we'd like to keep those at the top of the section

**Comment by scarabeusiv** [comment]
Could you give me also absolutely desired output? Or just commit the test :)
Even if the %pattern_basetechnologies should stay on top and stuff like that...

**Comment by scarabeusiv** [comment]
done
