### ISSUE TITLE
Not all license tags reformatted to spdx3 format

### ISSUE THREAD

**Issue by DimStar77** [openSUSE/spec-cleaner#226]
A spec file with this license is 'ignored' by spec cleaner:

```License:        LGPL-2.1+ AND GPL-2.0+```

The expectation would be to move that to SPDX3.0 format.

if 'AND` is written lowercase, it is being converted (the spec for SPDX2.x also had AND in caps, so this is a perfectly valid license string)

**Comment by scarabeusiv** [comment]
Closing as fixed per above
