### ISSUE TITLE
%{_libexecprefix} different on openSUSE and Fedora

### ISSUE THREAD

**Issue by toabctl** [openSUSE/spec-cleaner#232]
The openstack/rpm-packaging project got recently some lint failures (using spec-cleaner) like:

```
-%dir %{_prefix}/lib/monasca
-%{_prefix}/lib/monasca/agent
+%dir %{_libexecdir}/monasca
+%{_libexecdir}/monasca/agent
```

On openSUSE Tumbleweed, I get:
```
$ rpmspec --eval '%{_libexecdir}'
/usr/lib
```

But according to [Fedoras doc](https://fedoraproject.org/wiki/Packaging:RPMMacros), it is:

```
%{_prefix}            /usr
%{_exec_prefix}       %{_prefix}
%{_libdir}            %{_exec_prefix}/%{_lib}
%{_libexecdir}        %{_exec_prefix}/libexec
```

**Comment by scarabeusiv** [comment]
This is correct behaviour.

If you install stuff to /usr/lib on Fedora then you screwed up, they don't allow /usr/lib.

**Comment by scarabeusiv** [comment]
And actually it seems the fedora installs the pyton stuff to /usr/lib, but some to libexec.

**Comment by scarabeusiv** [comment]
Solution to fix this would be to detect if _libexecdir on the spec-cleaner side evals to the /usr/lib prior the replacements.

**Comment by scarabeusiv** [comment]
Added an option to change this behaviour as needed.
