### ISSUE TITLE
replace /usr with %{_prefix}

### ISSUE THREAD

**Issue by plusky** [openSUSE/spec-cleaner#43]
Example:
python scons/scons.py PREFIX=/usr ==> python scons/scons.py PREFIX=%{_prefix}

**Comment by scarabeusiv** [comment]
If I could point your eyes to file rpmsection.py There is function replace_known_dirs which needs tweaking. Could you do it?

**Comment by plusky** [comment]
OK, will look at it

**Comment by plusky** [comment]
closing as it is merged
