### ISSUE TITLE
remove %debug_package

### ISSUE THREAD

**Issue by plusky** [openSUSE/spec-cleaner#48]
Currently of no use, yet still resides in some ancient packages

**Comment by scarabeusiv** [comment]
While at it, we should also delete:

Vendor:
Icon:
Copyright:
Packager:

Lines...

**Comment by scarabeusiv** [comment]
This on the other hand looks slightly complex so I shall do it.

**Comment by scarabeusiv** [comment]
About that %debug_package:

You need to add new part to rpmprune.py and add new section macro to rpmregexp.py

**Comment by scarabeusiv** [comment]
(and also add some testcase :P

**Comment by scarabeusiv** [comment]
And done
