### ISSUE TITLE
Old-fashioned transform of make install line.

### ISSUE THREAD

**Issue by jengelh** [openSUSE/spec-cleaner#52]
spec-cleaner-0.6.8 changes
```
%install
%makeinstall
```
into
```
make DESTDIR=%{buildroot} install %{?_smp_mflags}
```
This should not be done anymore; the current best practice is to use `%make_install`.

**Comment by sleep-walker** [comment]
This is feature, not bug.

What makes that 'current best practice' when we are the only distribution, which use that? If you want to have package which builds against any other RPM distribution supported by OBS, you have to _not use_ this macro.

**Comment by jengelh** [comment]
Well yes, for older distros with pre-4.10 (IIRC), the long form is needed. However, people also run spec-cleaner for packages targeted expressly for modern rpm carriers (like openSUSE:Factory) only, for which this transform is just very verbose.
Sometimes, it may even be wrong, namely when there's a crappy Makefile that fails to properly handle -j/-l from _smp_mflags. I am worried that s-c is changing the modus operandi of the spec, too.

**Comment by sleep-walker** [comment]
I'm afraid that I don't recognize your versioning. My experience at the moment of implementation quite recent. I maintained Enlightenment for all RPM distributions supported by OBS. Even now your build would fail against SLE11, all Fedoras and CentOS.

Yes, using _smp_mflags may lead to problems. It is always good to report these bugs to upstream whenever it is possible so build and installation can scale better. And till you (or upstream) fix your package, you can enforce non-parallel build or installation with `-j 1'.

Could you please write your opinions and concerns about spec-cleaner to opensuse-packaging mailing list and leave bug tracker for technical issues, please?

**Comment by plusky** [comment]
In regard of supposed "best practise", I would like to mention that apart from opensuse packaging guidelines (which were according to history of edit mostly edited by @jengelh - see https://en.opensuse.org/index.php?title=openSUSE:Build_system_recipes&action=history ), fedora for example says "... Instead, Fedora packages should use: %make_install (Note the "_" !), make DESTDIR=%{buildroot} install or make DESTDIR=$RPM_BUILD_ROOT install. Those all do the same thing." - for details see http://fedoraproject.org/wiki/Packaging:Guidelines . So in my opinion safest possible way is to stay with make DESTDIR=%{buildroot} install %{?_smp_mflags}

**Comment by scarabeusiv** [comment]
We actually wanted to go with %make_install.
Problem was as stated already above the non-availability of such in the old/other distros.

Current logic is if there is %make_install it is kept and not altered. If anything else is used it sets the make install DESTDIR.

If the requisite change at some point (ie old distros finaly die) we will more than happily switch to macro itself.

Wrt the parallel install we did some tests in 2k10 with Diego Peterno about this and determined the thing is way faster when doing stuff in parallel, esp on ssd/in ram. So it is quite good default where people can override it with -j1, like with normal make.
