### ISSUE TITLE
Incorrect removal of .la files

### ISSUE THREAD

**Issue by jengelh** [openSUSE/spec-cleaner#53]
spec-cleaner-0.6.8 turns

```
find %{buildroot}%{_libdir} -name "*.la" -delete -print
```

into

```
find %{buildroot} -type f -name "*.la" -delete -print
```

which is wholeheartedly wrong. .la files may only be autoremoved from paths searched by default by the runtime linker.
The .la file records the path the file lives in, and libtool requires that so as to pass -Wl,-rpath,/opt/foo/lib to the link editor. In the absence of the .la file, that rpath entry won't be made and the program will not run. I therefore consider it an error to remove .la files from places other than /lib(64), /usr/lib(64) and /usr/lib/<tuple> (the Debian case). This also means that autoremoving /usr/lib(exec)/prog/libfoo.la is also incorrect.

Suggest to replace with:

```
rm -fv "%buildroot/%_libdir"/*.la
```

**Comment by scarabeusiv** [comment]
This is possible bug. There indeed might be cases where .la should be kept (like libtool plugins) but we decided to make it as broad as possible as in 99% of cases you simply don't want them at all.

Note that this practice is taken from gentoo where new EAPI actually wipes out all .la files and nothing happens.

Maybe we could try to check the .la content and determine if it is plugin. Always best for such packages would be tho to explicitly state the .la files in the %files section to be 100% safe.

**Comment by sleep-walker** [comment]
I'm pretty satisfied with the current state and I'd invest time when we meet package which gets broken by spec-cleaner. Does anyone know some?

**Comment by plusky** [comment]
I would also like to know if there actually is such package.

**Comment by jengelh** [comment]
There are about 4700 .la files outside the standard dirs, though many of them are likely referring to modules. The ones in /opt likely are not, though.

**Comment by plusky** [comment]
So far there was no case of actual breakage caused by this behavior of spec-cleaner, and claim of 4700 .la files seems to be unfounded as well.
