### ISSUE TITLE
Pointless renaming of "URL" rpm tag

### ISSUE THREAD

**Issue by jengelh** [openSUSE/spec-cleaner#55]
spec-cleaner-0.6.8 changes
```
-URL:            http://libevent.org/
+Url:            http://libevent.org/
```
This is just plain weird. URL is an acronym and deserves to *remain* uppercased.

**Comment by sleep-walker** [comment]
This is feature, not bug. Intention of this change is to unify the look and make the review easier. Lets have moment of silence for good old uppercased acronym. It deserves that. :)

**Comment by jengelh** [comment]
If it's a feature, then the bug is that BuildRequires: is not changed to Buildrequires:.

**Comment by scarabeusiv** [comment]
It is feature. There, when there was choice of two options, was check what is most used in our packages (Url won) and then we asked if people were okay with it (which they were), so in terms of unification we simply stick to one of the posible alternatives.

TBH I never seen somebody use Buildrequires:...
