### ISSUE TITLE
%reconfigure_fonts_scriptlets incorrect curlification

### ISSUE THREAD

**Issue by plusky** [openSUSE/spec-cleaner#57]
%reconfigure_fonts_scriptlets is changed to %{reconfigure_fonts_scriptlets}

**Comment by plusky** [comment]
And same for %reconfigure_fonts_prereq

**Comment by scarabeusiv** [comment]
Fixed by commit 72fcd006ed3a7898215cdf9b6c1bed0f39946ffa
