### ISSUE TITLE
superfluous braces around macro function

### ISSUE THREAD

**Issue by peterph** [openSUSE/spec-cleaner#60]
`%__os_install_post` gets updated to `%{__os_install_post}`, namely:

    %{expand:%%global __os_install_post {%__os_install_post
    ...
    }}

becomes

    %{expand:%%global __os_install_post {%{__os_install_post}
    ...
    }}

It might be better to leave it as-is like other nullary functional macros.

**Comment by scarabeusiv** [comment]
Aaand done.
