### ISSUE TITLE
wrong curlification

### ISSUE THREAD

**Issue by plusky** [openSUSE/spec-cleaner#61]
In following case, spec-cleaner wrongfully curlifies "%f"
-for i in $(find %{_builddir}/sqlite3%{_bindir} -type f -printf "%f\n"); do
+for i in $(find %{_builddir}/sqlite3%{_bindir} -type f -printf "%{f}\n"); do

**Comment by sleep-walker** [comment]
I think that this is correct behaviour and you should escape your '%f'.

for i in $(find %{_builddir}/sqlite3%{_bindir} -type f -printf "%%f\n"); do

It works only because you don't have macro %f defined.

**Comment by scarabeusiv** [comment]
Oh crap, I didin't realize this.

Btw I wanted to drop by and tell you propper aproach how to do it anyway. But Tomas is right. It should've been escaped! :)

**Comment by plusky** [comment]
Closing issue while ashamed for not properly escaping :(
