### ISSUE TITLE
%{?_smp_mflags} not added to make with certain parameters

### ISSUE THREAD

**Issue by plusky** [openSUSE/spec-cleaner#63]
Following is let untouched by spec-cleaner:
make xpm_libs="-L/usr/X11R6/%{_lib} -lXpm -lX11"

should be:
make xpm_libs="-L/usr/X11R6/%{_lib} -lXpm -lX11" %{?_smp_mflags}

**Comment by scarabeusiv** [comment]
Tomas you did the last touches in there.

**Comment by scarabeusiv** [comment]
As discssed offline if the make gets too ugly we keep it to leave it up to the maintainer decision, too risky to add everywhere.
