### ISSUE TITLE
Don't bracketize every macro

### ISSUE THREAD

**Issue by Mailaender** [openSUSE/spec-cleaner#65]
`%files_fontsconf_file -l 57-adobe-sourcehansans.conf` 

will break if it becomes

`%{files_fontsconf_file} -l 57-adobe-sourcehansans.conf`

**Comment by scarabeusiv** [comment]
Thanks for the report I updated the exclude bracketing:

The logic is about putting the brackets around variables while command macroes should be left plain. If you find some other done wrongly feel free to update the excludes_bracketing.txt file or just filling another issue.

**Comment by Mailaender** [comment]
Thanks for the quick fix!
