### ISSUE TITLE
'stat' format sequences shouldn't be put in brackets

### ISSUE THREAD

**Issue by kstreitova** [openSUSE/spec-cleaner#66]
'stat' format sequences are wrongly put in brackets that causes their incorrect evaluation:

before spec-cleaner: 
echo \`stat --format="%y" ~\`

output:
2015-05-04 10:38:50.031128333 +0200

--------

after spec-cleaner: 
echo \`stat --format="%{y}" ~\`

output:
?y}

**Comment by sleep-walker** [comment]
You should properly escape your input ('%%y' is proper way) or do you expect to have %y macro?

**Comment by scarabeusiv** [comment]
As Tomas said. You actually have to use %%y otherwise if you define bit up something like:

%define y "fuuuuu<Censored>"

it would get expanded in your date call. So the echo line should be "--format="%%y"".
