### ISSUE TITLE
INcorrect modification in URL

### ISSUE THREAD

**Issue by weberhofer** [openSUSE/spec-cleaner#71]
I'm using spec-cleaner-0.7.1 and it works very well. Today I've noticed a tiny bug:

In the line 
```
Source0: http://downloads.sourceforge.net/project/e1000/e1000e%20stable/%{version}/e1000e-%{version}.tar.gz"
```
the section ```e1000e%20stable``` is converted to ```e1000e{%20stable}``` which is incorrect.

The full spec can be found in https://build.opensuse.org/package/show/hardware/intel-e1000e

**Comment by sleep-walker** [comment]
Thank you for your words of appreciation and for your report.

It is indeed incorrect in several ways.

1] you probably want to transform %20stable to %%20stable so macro expansion wouldn't happen
2] in this case %20stable is taken as correct macro name and in fact it is not - macro name can't start with number
3] replacement is incorrect as %{20stable} is expected, but scarabeus just verified that you probably made just typo (or at least the recent version behaves correctly)

For you is important the 1] part to "fix" your spec file and learn why it did the replacement correctly.

For me is to fix regexp to ignore macros with number prefix.

**Comment by weberhofer** [comment]
thank you.
