### ISSUE TITLE
incorrect KMP macros handling

### ISSUE THREAD

**Issue by plusky** [openSUSE/spec-cleaner#72]
after spec-cleaner treatement, package fails to build:
 diff sysdig.spec sysdig.spec.old 
27,28d26
< BuildRequires:  %{kernel_module_package_buildreqs}
< BuildRequires:  cmake >= 2.8.2
29a28,29
> BuildRequires:  %kernel_module_package_buildreqs
> BuildRequires:  cmake >= 2.8.2
33d32
< BuildRequires:  ncurses-devel
34a34
> BuildRequires:  ncurses-devel
36c36,37
< %{kernel_module_package} -p %{name}-kmp-preamble
---
> 
> %kernel_module_package -p %{name}-kmp-preamble
65c66
< make %{?_smp_mflags} VERBOSE=1
---
> make VERBOSE=1
73,74c74,75
< for flavor in %{flavors_to_build} ; do
<       make KERNELDIR="%{_prefix}/src/linux-obj/%{_target_cpu}/$flavor" \
---
> for flavor in %flavors_to_build ; do
>       make KERNELDIR="/usr/src/linux-obj/%_target_cpu/$flavor" \
95a97
> 

build fails as following:
[   20s] + exec rpmbuild -ba --define '_srcdefattr (-,root,root)' --nosignature --define '_build_create_debug 1' /home/abuild/rpmbuild/SOURCES/sysdig.spec
[   21s] arch/x86/Makefile:129: CONFIG_X86_X32 enabled but no binutils support
...

**Comment by plusky** [comment]
http://paste.opensuse.org/view/raw/9070181

**Comment by scarabeusiv** [comment]
Just add it to excludes, the %kernel_module_package should be uncurlified.

It is actually excluded on %suse_kernel_module_package already so it is just overlook

**Comment by sleep-walker** [comment]
There are better diff formats than the default one.

**Comment by scarabeusiv** [comment]
Fixed in git 9a68b9f273298c24c909d1ec3ca32dcce4414232
