### ISSUE TITLE
%{?jobs:-j%{jobs}} not transformed in install section

### ISSUE THREAD

**Issue by plusky** [openSUSE/spec-cleaner#73]
%build
-%__make %{?jobs:-j%{jobs}} \
-    CC="%__cc" \
+make %{?_smp_mflags} \

 %install
-%__make %{?jobs:-j%{jobs}} \
+make %{?jobs:-j%{jobs}} \

**Comment by sleep-walker** [comment]
It seems that '%{?jobs:-j%{jobs}}' is some remnant of old openSUSE packaging and could be transformed into %{?_smp_mflags} as well. Good idea.

**Comment by plusky** [comment]
Sure it was apg - https://build.opensuse.org/package/view_file/security/apg/apg.spec?expand=1
