### ISSUE TITLE
make options should be placed before positional parameters

### ISSUE THREAD

**Issue by hwoarang** [openSUSE/spec-cleaner#87]
I got the following diff when I run it against a spec file on one of my packages
```
 %install
-make %{?_smp_mflags} DESTDIR=%{buildroot} install
+make DESTDIR=%{buildroot} install %{?_smp_mflags}
```
I believe this is wrong. -j is a 'make' option and it should be right next to 'make' instead of being place at the end. I believe the original code in the spec file is better than the one suggested by spec-cleaner. Or at least, spec-cleaner shouldn't try to reorder it and accept either case.

**Comment by scarabeusiv** [comment]
This was already fixed I fear, do you know which version of spec-cleaner you have and could you verify it is 0.7.8 or newer?

**Comment by scarabeusiv** [comment]
See issue #77

**Comment by hwoarang** [comment]
Ah right. Sorry about that. I am on Leap so I have 0.7.5. I will wait for a new version to hit Leap then :)
