### ISSUE TITLE
do pypi releases

### ISSUE THREAD

**Issue by toabctl** [openSUSE/spec-cleaner#95]
OpenStack has an [rpm-packaging initiative](https://wiki.openstack.org/wiki/Rpm-packaging) and we are currently looking for a spec file checker to get common formatting into the spec files.
To create a testing job we need a released version on pypi.
Is it possible that you do regular releases on pypi wheever you create a new tag?

**Comment by scarabeusiv** [comment]
Is it possible to automate it? I never put anything on pypi so I have no clue how complex it is and how it should be done.
Also you should have commit access (everyone in openSUSE project should) to the repo so if you know how to set it up, feel free :)

**Comment by toabctl** [comment]
Not sure about automation. But I did a manual release of 0.7.9 via ```python setup.py sdist upload``` (given that your ```~/.pypirc``` is setup correct). Maybe we can add a ```RELEASE.md``` file containing the steps howto do a release (1. tag, 2. upload to pypi, 3. post release version bump)

**Comment by toabctl** [comment]
Ah. And if you have a pypi account, tell me that name so I can add you as admin...

**Comment by scarabeusiv** [comment]
Username is scarabeus, I just created the account.

Anyway if you create the release.md it should probably work for me so I won't forget to do it :)
