### ISSUE TITLE
excludes-bracketing not allways excluded

### ISSUE THREAD

**Issue by plusky** [openSUSE/spec-cleaner#99]
Following should be excluded from bracketing (are mentioned in excludes-bracketing.txt) but are bracketed anyway
%{service_(add|del)}_[^\s]*
%{yast_(build|install)}[^\s]*

**Comment by scarabeusiv** [comment]
Nope it works. But you can't just copy it.

You need to check for %{yastbuild}WHITESPACE and %{yastinstall}WHITESPACE respectively.

The same applies fo rht eservice_bla
